voy aDate:  30/11/2019.

Fecha: 30/11/2019.

Title:  Open edX.

Título: Open edX.

URL: open.edx.org.

Category: e-learning.

Categoría: e-learning.

Description: E-learning software platform, collaboration between multiple USA universities.

Descripción: Software para e-learning, una colaboración entre múltiples universidades estadounidenses.

Notes: See the "tutor" software for more details.

Notas: Vea el software "tutor" para más detalles.
