Date:  01/12/2019.

Fecha: 01/12/2019.

Title:  Pencil Project.

Título: Pencil Project.

URL: `pencil.evolus.vn <https://pencil.evolus.vn>`_.

Category: design.

Categoría: diseño.

Description: Wireframes design tool.

Descripción: Herramienta de diseño de wireframes.

.. image:: https://gitlab.com/constrict0r/observatory/raw/master/img/pencil.png
   :alt: pencil

Installation:

.. code-block:: bash

 wget https://pencil.evolus.vn/dl/development/pencil_3.1.0.20191202003002_amd64.deb
 sudo dpkg -i ~/Descargas/pencil_3.1.0.20191202003002_amd64.deb
 sudo chmod 4755 chrome-sandbox

Instalación:

.. code-block:: bash

 wget https://pencil.evolus.vn/dl/development/pencil_3.1.0.20191202003002_amd64.deb
 sudo dpkg -i ~/Descargas/pencil_3.1.0.20191202003002_amd64.deb
 sudo chmod 4755 chrome-sandbox

Commands:

.. code-block:: bash

 pencil => Executes pencil.

Comandos:

.. code-block:: bash

 pencil => Ejecuta pencil.

Pros:
 - Easy to use.
 - Rapid prototiping.
 - Exports to different formats including html + css + js.
 - The quality of the html + css + js generated code is decent.

Pros:
 - Fácil de usar.
 - Prototipado rápido.
 - Exporta a diferentes formatos incluido html + css + js.
 - La calidad de html + css + js es aceptable.

Cons:
 - Hard to install (Buster crashes installing with stable release, works fine
   with nightly build)
 - On the downloads page says - "the Firefox extension bases on an older
   version of Pencil which is no longer in active development". Gives 404
   error.
 - Must install the 'Generic Wireframe set of figures/objects' to have a
   decent set of forms to work with.
 - By default, when exporting to an html prototype, the background color must
   always be manually set to #FFF (white).
 - When creating a new page if you don't put a solid color (as white), you
   cannot change it later.

Contras:
 - Díficil de instalar (En Buster se cae instalando con versión oficial, la
   versión 'nigthly build' funciona bien).
 - En la página de descargas dice: "the Firefox extension bases on an older
   version of Pencil which is no longer in active development". Da error 404.
 - Se debe instalar el 'Conjunto génerico de figuras/objetos para wireframes'
   para tener un conjunto decente de formas con las cuales trabajar.
 - De manera predeterminada, cuando se exporta a un prototipo html, el color
   de fondo siempre debe de ponerse a mano como #FFF (blanco).
 - Cuando se crea una nueva página, si no pones un color sólido (como blanco),
   no puedes cambiarlo luego.