Date:  01/12/2019.

Fecha: 01/12/2019.

Title:  Pencil Project.

Título: Pencil Project.

URL: `pencil.evolus.vn <https://pencil.evolus.vn>`_.

Category: design.

Categoría: diseño.

Description: Wireframes design tool.

Descripción: Herramienta de diseño de wireframes.

.. image:: https://gitlab.com/constrict0r/observatory/raw/master/img/pencil.png
   :alt: pencil

Installation:

.. code-block:: bash

 sudo chmod 4755 chrome-sandbox
 wget https://pencil.evolus.vn/dl/development/pencil_3.1.0.20191202003002_amd64.deb
 sudo dpkg -i ~/Descargas/pencil_3.1.0.20191202003002_amd64.deb
 sudo chmod 4755 chrome-sandbox

Instalación:

.. code-block:: bash

 sudo apt install chrome-sandbox
 wget https://pencil.evolus.vn/dl/development/pencil_3.1.0.20191202003002_amd64.deb
 sudo dpkg -i ~/Descargas/pencil_3.1.0.20191202003002_amd64.deb
 sudo chmod 4755 chrome-sandbox

Commands:

.. code-block:: bash

 pencil => Executes pencil.

Comandos:

.. code-block:: bash

 pencil => Ejecuta pencil.

Cons:
 - On Debian Buster crashes on installing with stable release, works fine with
   nightly build
 - On the downloads page says - "the Firefox extension bases on an older
   version of Pencil which is no longer in active development". Gives 404
   error.

Contras:
 - En Debian Buster se cae instalando con la versión oficial, con una versión
   'nigthly build' funciona bien.
 - En la página de descargas dice: "the Firefox extension bases on an older
   version of Pencil which is no longer in active development". Da error 404.
