Date:  01/12/2019.

Fecha: 01/12/2019.

Title:  Pencil2D.

Título: Pencil2D.

URL: pencil2d.org.

Category: design.

Categoría: diseño.

Description: 2D drawing software that can be used for web sites wireframing.

Descripción: Software de dibujo 2D que puede usarse para crear esquemas de
             sitios web.

.. image:: https://gitlab.com/constrict0r/observatory/raw/master/img/pencil2d.png
   :alt: pencil2d

Installation:

.. code-block:: bash

 sudo apt install pencil2d

Instalación:

.. code-block:: bash

 sudo apt install pencil2d

Pros:
 - Simple.
 - Easy to install.
 - Easy to use.

Pros:
 - Simple.
 - Fácil de instalar.
 - Fácil de usar.

Cons:
 - Does not generate code neither interactions (html, js, css).

Contras:
 - No genera código ni interacciones (html, js, css).
