Date:  30/11/2019.

Fecha: 30/11/2019.

Title:  swagger-editor.

Título: swagger-editor.

URL: `swagger-editor <https://swagger.io/docs/open-source-tools/swagger-editor>`_.

Category: editors.

Categoría: editores.

Description: Openapi web editor.

Descripción: Editor web para openapi.

.. image:: https://gitlab.com/constrict0r/observatory/raw/master/img/swagger-ditor.png
   :alt: swagger-editor

Installation:

.. code-block:: bash

 sudo apt install -y docker
 docker pull swaggerapi/swagger-editor
 docker run -p 80:8080 swaggerapi/swagger-editor
 visit 127.0.0.1

Instalación:

.. code-block:: bash

 sudo apt install -y docker
 docker pull swaggerapi/swagger-editor
 docker run -p 80:8080 swaggerapi/swagger-editor
 visite 127.0.0.1
