Date:  <xx/xx/xxxx>.

Fecha: <xx/xx/xxxx>.

Title:  <Write me>.

Título: <Escríbeme>.

URL: <Main site goes here, don't use 'https' or colon or sphinx will crash>.

Category: <I.e.: editors, multimedia, security>.

Categoría: <Ej: editores, multimedia, seguridad>.

Description: <Write the software description and/or purpose here>.

Descripción: <Escriba la descripción y/o próposito del software aquí>.

.. image:: https://gitlab.com/constrict0r/observatory/raw/master/img/title.png
   :alt: title

Installation:

.. code-block:: bash

 <Write all installation steps here>.
 <Another installation step here>.

Instalación:

.. code-block:: bash

 <Escriba todos los pasos de instalación aquí>.
 <Otro paso de instalación aquí>.

Commands:

.. code-block:: bash

 <Command 1 => Does something>.
 <Command 2 => Does something else>.

Comandos:

.. code-block:: bash

 <Comando 1 => Hace algo>.
 <Comando 2 => Hace otra cosa>.

Pros:
 - <Pro #01>.

Pros:
 - <Pro #01>.

Cons:
 - <Con #01>.

Contras:
 - <Contra #01>.

Notes: <Write your notes here>.

Notas: <Escribe tus notas aquí>.
