Date:  <xx/xx/xx>.

Fecha: <xx/xx/xx>.

Title:  <Write me>.

Título: <Escríbeme>.

URL: <Paste the software main site here>.

Description: <Write the software description and/or purpose here>.

Descripción: <Escríbeme>.

Installation:

.. code-block:: bash

 <Write all installation steps here>.
 <Another installation step here>.

Instalación:

.. code-block:: bash

 <Escriba todos los pasos de instalación aquí>.
 <Otro paso de instalación aquí>.

Commands:

.. code-block:: bash

 <Command 1 => Does something>.
 <Command 2 => Does something else>.

Comandos:

.. code-block:: bash

 <Comando 1 => Hace algo>.
 <Comando 2 => Hace otra cosa>.

Pros:
 - <Pro #01>.

Pros:
 - <Pro #01>.

Cons:
 - <Con #01>.

Contras:
 - <Contra #01>.

Notes: <Write your notes here>.

Notas: <Escribe tus notas aquí>.
